name: TESTING comiled win10 version

on: workflow_dispatch

jobs:
          
  build-wheels:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip requirements
        run: |
          python -m pip install -U pip setuptools wheel build
          python -m pip install -r requirements.txt
      - name: Setup and install win_x86_64 wheel
        run: |
          python setup.py bdist_wheel --plat-name=win_x86_64
          python -m pip install dist/*-win*.whl
      - uses: actions/upload-artifact@v2
        with:
          name: wheel-${{ matrix.python-version }}
          path: dist/*-win*.whl
